/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ClientList: (typeof import("./components/ClientList.vue"))["default"]
    ClientPanel: (typeof import("./components/ClientPanel.vue"))["default"]
    ClientSearch: (typeof import("./components/ClientSearch.vue"))["default"]
    ClientTry: (typeof import("./components/ClientTry.vue"))["default"]
    DashboardBreadcrumbs: (typeof import("./components/DashboardBreadcrumbs.vue"))["default"]
    DashboardPanel: (typeof import("./components/DashboardPanel.vue"))["default"]
    DefaultFooter: (typeof import("./components/DefaultFooter.vue"))["default"]
    DefaultHeader: (typeof import("./components/DefaultHeader.vue"))["default"]
    RouterLink: (typeof import("vue-router"))["RouterLink"]
    RouterView: (typeof import("vue-router"))["RouterView"]
    SearchDrawer: (typeof import("./components/SearchDrawer.vue"))["default"]
  }
}
